default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
test:
  <<: *default
  database: <%= ENV["DB_NAME_TST"] %>
  username: <%= ENV["DB_USER_TST"] %>
  password: <%= ENV["DB_SECRET_TST"] %>
development:
  <<: *default
  database: <%= ENV["DB_NAME_DEV"] %>
  username: <%= ENV["DB_USER_DEV"] %>
  password: <%= ENV["DB_SECRET_DEV"] %>
production:
  <<: *default
  database: <%= ENV["DB_NAME_PROD"] %>
  username: <%= ENV["DB_USER_PROD"] %>
  password: <%= ENV["DB_SECRET_PROD"] %>
